inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
